export class stencilIconStateMap {
	public static readonly stateMap = {
		primary: 'primary',
		secondary: 'secondary',
		'non-action': 'non-action',
		boxed: 'boxed',
		'primary-button': 'primary-button',
		'secondary-button': 'secondary-button',
		'secondary-button-hover': 'secondary-button-hover',
		'tertiary-button': 'tertiary-button',
		success: 'success',
		gain: 'success',
		'success-alternate': 'success-alternate',
		error: 'error',
		loss: 'error',
		alert: 'error',
		warning: 'warning',
		informational: 'informational',
		new: 'new',
		attention: 'new',
		checkbox: 'checkbox',
		neutral: 'neutral',
		'primary-danger-button': 'primary-danger-button',
		'secondary-danger-button': 'secondary-danger-button',
		'tertiary-danger-button': 'tertiary-danger-button',
		'progress-active': 'progress-active',
		toggle: 'toggle',
		'toggle-hover': 'toggle-hover',
	};
}
